### ISSUE TITLE
Module improvements

### ISSUE THREAD

**Issue by atinux** [agility/agilitycms-nuxt-module#1]
Hey, thanks for making a Nuxt module for Agility CMS ❤️ 

Some areas to improve:
- Use latest ES syntax here: https://github.com/agility/agilitycms-nuxt-module/blob/main/lib/agility-module.js (use `import` instead of `require`)
- I don't recommend to use `process.cwd()` here: https://github.com/agility/agilitycms-nuxt-module/blob/main/lib/agility.sync.js#L11, instead, you may use `nuxt.options.rootDir` instead that you can FW from https://github.com/agility/agilitycms-nuxt-module/blob/main/lib/agility-module.js#L24

**Comment by joelvarty** [comment]
Thanks for the feedback! We'll look to make these updates soon.
